services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres17_rbac
    restart: always
    environment:
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: orders
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: